# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
- main

pool:
  vmImage: ubuntu-latest
jobs:
  - job: build
    steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'

    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
      displayName: 'Run a multi-line script'
    - script: pwd
    - script: find ./
    - task: Gradle@2
      inputs:
        gradleWrapperFile: 'gradlew'
        tasks: 'clean build -x test'
        workingDirectory: ''
        publishJUnitResults: false
        testResultsFiles: '**/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        sonarQubeRunAnalysis: false
        sqGradlePluginVersionChoice: 'specify'
        sonarQubeGradlePluginVersion: '2.6.1'
    - script: find ./
    - script: pwd
    - script: echo $(Build.ArtifactStagingDirectory)
    - script: echo $(System.DefaultWorkingDirectory) 
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: build/libs/sleuth-kafka-streams-0.0.1-SNAPSHOT.jar'
        ArtifactName: 'drop'
        publishLocation: 'Container'